# Generated by Django 5.2.1 on 2025-05-25 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('seats_booked', models.PositiveIntegerField()),
                ('trip_type', models.CharField(choices=[('single', 'Single Trip'), ('round', 'Round Trip')], default='single', max_length=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flights')),
                ('return_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bookings', to='flights.flights')),
            ],
        ),
    ]
