# Generated by Django 5.2.1 on 2025-06-03 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('num_seats', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=10)),
                ('flight_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flights')),
            ],
        ),
    ]
