# Generated by Django 5.2.1 on 2025-05-30 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
