# Generated by Django 5.2.1 on 2025-05-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contact_number',
        ),
    ]
