# Generated by Django 5.2.1 on 2025-05-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='airport_images/'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='contact',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='terminals',
            field=models.IntegerField(),
        ),
    ]
