# Generated by Django 5.2.1 on 2025-05-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
