# Generated by Django 5.2.1 on 2025-05-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_airport_image_alter_airport_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
