# Generated by Django 5.2.1 on 2025-05-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20, unique=True)),
                ('airline', models.CharField(max_length=100)),
                ('departure_city', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_capacity', models.PositiveIntegerField(default=180)),
                ('available_seats', models.PositiveIntegerField(default=180)),
                ('is_international', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flight_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default='Economy', max_length=50)),
            ],
        ),
    ]
