# Generated by Django 5.2.1 on 2025-06-10 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=100)),
                ('departure_time', models.CharField()),
                ('arrival_time', models.CharField()),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_capacity', models.PositiveIntegerField(default=180)),
                ('available_seats', models.PositiveIntegerField(default=180)),
                ('is_international', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flight_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('economy', 'economy'), ('business', 'business')], max_length=50)),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_arr_airport', to='airport.airport')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_dep_airport', to='airport.airport')),
            ],
        ),
    ]
