# Generated by Django 5.2.1 on 2025-05-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='flight_number',
            field=models.CharField(max_length=20),
        ),
    ]
